apiVersion: apps/v1
kind: Deployment
metadata:
  name: pythonserver
  labels:
    app: flask
spec:
  selector:
    matchLabels:
      app: flask
  replicas: 3
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: python-app
        image: karin86/pythonapp:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
          name: flask-container
---
apiVersion: v1
kind: Service
metadata:
  name: pythonservices
  labels:
    app: flask
spec:
  ports:
  - port: 5000
    protocol: TCP
    name: flask
  selector:
    app: flask
  type: LoadBalancer
